### ISSUE TITLE
Not finding episodes on Torrent9 because of quality naming

### ISSUE THREAD

**Issue by r4ph0u** [pymedusa/medusa.github.io#99]
Branch : master (fetched and pulled)
OS: Raspbian Stretch
Python version : Python 2.7.13

I'm unable to get episodes from Torrent9 because of the naming.
Most of the files are HDTV, but the name only contains "HDTV" and not "720p" so Medusa il just ignoring them.

**Comment by p0psicles** [comment]
Use quality unknown.

**Comment by medariox** [comment]
I've just tried it and it works also just fine with `SDTV` and `720p`.

**Comment by medariox** [comment]
It's fixed in develop, not master. You need to either switch to develop or wait for the next release.

**Comment by r4ph0u** [comment]
Still not working with "any" quality or even "unknown". So it's probably not a naming issue. Any clue ?

**Comment by medariox** [comment]
What version are you running? Does a manual search return any results?

**Comment by r4ph0u** [comment]
```
Medusa Info: | Branch: masterCommit: d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebeVersion: v0.2.1Database: 44.9
-- | --
```

A manual search is not working either
```
2018-04-08 18:51:56 INFO     SEARCHQUEUE-MANUAL-153021 :: [d6eb72d] Unable to find manual results for: The Walking Dead - S08E14 - 
2018-04-08 18:51:56 INFO     SEARCHQUEUE-MANUAL-153021 :: [Yggtorrent] :: [d6eb72d] Performing season pack search for The Walking Dead
2018-04-08 18:51:56 WARNING  SEARCHQUEUE-MANUAL-153021 :: [Yggtorrent] :: [d6eb72d] Unable to connect to provider
2018-04-08 18:51:54 INFO     SEARCHQUEUE-MANUAL-153021 :: [Yggtorrent] :: [d6eb72d] Performing episode search for The Walking Dead
2018-04-08 18:51:54 INFO     SEARCHQUEUE-MANUAL-153021 :: [Torrent9] :: [d6eb72d] Performing season pack search for The Walking Dead
2018-04-08 18:51:53 INFO     SEARCHQUEUE-MANUAL-153021 :: [Torrent9] :: [d6eb72d] Performing episode search for The Walking Dead
2018-04-08 18:51:53 INFO     SEARCHQUEUE-MANUAL-153021 :: [d6eb72d] Using manual search providers
2018-04-08 18:51:53 INFO     SEARCHQUEUE-MANUAL-153021 :: [d6eb72d] Building internal name cache for The Walking Dead
2018-04-08 18:51:53 INFO     SEARCHQUEUE-MANUAL-153021 :: [d6eb72d] Finished processing 2683 scene exceptions.
2018-04-08 18:51:53 INFO     SEARCHQUEUE-MANUAL-153021 :: [d6eb72d] Updating exception_cache and exception_season_cache
2018-04-08 18:51:53 INFO     SEARCHQUEUE-MANUAL-153021 :: [d6eb72d] Beginning manual search for: The Walking Dead - S08E14 - 
```

**Comment by medariox** [comment]
You are still on master.

> It's fixed in develop, not master. You need to either switch to develop or wait for the next release.

**Comment by r4ph0u** [comment]
I thought you were saying that for le YGG issue, sorry about that..
Thanks for your time

**Comment by r4ph0u** [comment]
@medariox A last question..
How does medusa is supposed to control the seed limit of my bittorent client (deluge) ? because it doesn't seems to work here. Is it because I'm using the blackhole method ?

**Comment by medariox** [comment]
Yes, you need to use a download client for that feature.

**Comment by OmgImAlexis** [comment]
Next time please use the correct issue tracker on https://github.com/pymedusa/Medusa
